---
- name: Installing Firefox (and other dependencies)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - firefox
    - python3-requests
  tags:
    - firefox
    - desktop

- name: Configure profiles
  include_tasks: configure_profile.yml
  loop: "{{ firefox_profiles | dictsort }}"
  loop_control:
    loop_var: firefox_profile
  tags:
    - firefox
    - desktop
