---
- name: Installing shell packages
  become: true
  apt:
    name: "{{ shell_packages }}"
    state: present
  tags:
    - shell
    - desktop
    - server

- name: Register current user (workaround to change default shell)
  shell: whoami
  register: current_user

- name: Change default shell to zsh
  become: true
  shell: "chsh -s $(which zsh) {{ current_user.stdout }}"
  register: build_output
  changed_when: build_output.rc != 0
  tags:
    - shell
    - desktop
    - server

- name: Checking if oh-my-zsh directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags:
    - shell
    - desktop
    - server

- name: Fetching oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 0755
  when: not oh_my_stats.stat.exists
  tags:
    - shell
    - desktop
    - server

- name: Install oh-my-zsh
  command: zsh /tmp/install-oh-my-zsh.sh
  when: not oh_my_stats.stat.exists
  tags:
    - shell
    - desktop
    - server

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - shell
    - desktop
    - server

- name: Install zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - shell
    - desktop
    - server

- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Remove default .zshrc as it'll be added by stow
  file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: absent