#!/usr/bin/env bash

declare -a exclusion=(install install-root scripts config original_backup README.md TODO)

in_array() {
    local haystack=${1}[@]
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done
    return 1
}

shopt -s nullglob

# making a backup of existing files in .dotfiles to .dotfiles/original_backup
echo 'Making a backup to .dotfiles/original_backup '
for f in ~/.dotfiles/*
do
	FILENAME=${f##*/}
	if in_array exclusion $FILENAME; then
		continue
	fi
	if [ -e ~/.$FILENAME ] && [ ! -L ~/.$FILENAME ]; then
		mkdir -p ~/.dotfiles/original_backup
		mv ~/.$FILENAME ~/.dotfiles/original_backup/
	fi

	ln -fsv $f ~/.$FILENAME
done

# create an ssh keys in case we don't have them yet
echo "Importing SHH key from LP if not found..."
if [ ! -e ~/.ssh/id_rsa ]; then
	ssh-import-id $LP_ID
  echo '...LP SSH key imported'
fi

# Installing required apps
echo 'Installing apps...'
chmod +x ~/.dotfiles/scripts/*.sh
~/.dotfiles/scripts/app_install.sh

# sourcing variables and replacing var values on files
source ~/.dotfiles/config/git/vars
tmpfile=$(mktemp)
cat ~/.dotfiles/bash_aliases | envsubst > "$tmpfile" &&  mv "$tmpfile" ~/.dotfiles/bash_aliases

# configuring useful work env stuff (scripts)
SCRIPT_DIR='my-scripts'
mkdir ~/$SCRIPT_DIR
for f in ~/.dotfiles/config/work-env/*
do
	FILENAME=${f##*/}
	if in_array exclusion $FILENAME; then
		continue
	fi
  echo "Creating symbolic link and alias for $FILENAME"
	ln -fsv $f ~/$SCRIPT_DIR/$FILENAME
  chmod +x $f
  echo "alias $(echo ${FILENAME/%'.sh'})=$HOME/$SCRIPT_DIR/$FILENAME" >> ~/.bash_aliases
done
source ~/.bash_aliases
