---
- name: Setup desktop machine
  hosts: desktop
  tags:
    - desktop
  roles:
    - base
    - shell
    - dotfiles
    - firefox
    - chrome
    - vscodium
    - virtualization

- name: Setup server machine
  hosts: server
  tags:
    - server
  roles:
    - base
    - shell
    - dotfiles
    - virtualization
