---
- name: Checking if there's already a .dotfiles directory
  stat:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
  register: dotfiles_dir

- name: Backup existing .dotfiles
  copy:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/old_backup"
  when: dotfiles_dir.stat.exists

- name: Create symbolic links for *rc configs
  become: true
  file:
    src: "{{ item }}"
    dst: "{{ lookup('env', 'HOME') }}/.{{ item }}"
    state: link
  loop: "{{ lookup('fileglob', 'files/rc-files/', wantlist=True) }}"

