---
- name: Adding GPG key of the VSCodium repo
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present
  tags:
    - vscodium
    - desktop

- name: "Adding VSCodium repo"
  apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    state: present
  tags:
    - vscodium
    - desktop

- name: "Installing VSCodium"
  apt:
    name: codium
    state: present
  tags:
    - vscodium
    - desktop

- name: Setting up VSCode marketplace for VSCodium
  copy:
    src: product.json
    dst: "~/.config/VSCodium"

- name: Installing VSCodium extensions
  shell: codium --install-extension {{ item }}
  loop:
    - "{{ extensions }}"
  tags:
    - vscodium
    - desktop

- name: Setting VSCodium as default diff tool (for git)
  shell: |
    git config --global diff.tool vscode
    git config --global difftool.vscode.cmd 'code --wait --diff $LOCAL $REMOTE' 
  tags:
    - vscodium
    - desktop