---
- name: Adding GPG key of the VSCodium repo
  become: true
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present
  tags:
    - vscodium
    - desktop

- name: "Adding VSCodium repo"
  become: true
  apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    state: present
  tags:
    - vscodium
    - desktop

- name: "Installing VSCodium"
  become: true
  apt:
    name: codium
    state: present
  tags:
    - vscodium
    - desktop

- name: Create a .config directory if needed
  file:
    path: $HOME/.config
    state: directory
    mode: '0755'

- name: Create user settings directory
  file:
    state: directory
    path: $HOME/.config/VSCodium/User
    mode: '0750'

- name: Setting up VSCode marketplace for VSCodium
  copy:
    src: product.json
    dest: $HOME/.config/VSCodium/User/VSCodium

- name: Installing VSCodium extensions
  command: "codium --install-extension {{ item }}"
  loop: "{{ extensions }}"
  tags:
    - vscodium
    - desktop

- name: Setting VSCodium as default diff tool (for git)
  shell: |
    git config --global diff.tool codium
    git config --global difftool.codium.cmd 'code --wait --diff $LOCAL $REMOTE' 
  tags:
    - vscodium
    - desktop