---
- name: Adding Chrome apt signing key
  become: true
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
  tags:
    - chrome
    - desktop

- name: Adding Chrome repo into sources list
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  tags:
    - chrome
    - desktop

- name: Installing google-chrome-stable
  become: true
  apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true
  tags:
    - chrome
    - desktop

- name: Create extensions directory if needed
  become: true
  file:
    path: "{{ chrome_extensions_dir }}"
    state: directory

- name: Install extensions
  include_tasks: install_extensions.yaml
  tags:
    - chrome
    - desktop