---
- name: Check host CPU virtualization support
  block:
    - name: Check host CPU required instruction set
      command: "egrep -c '(vmx|svm)' /proc/cpuinfo"
      register: cpuinfo_output
      failed_when: cpuinfo_output.stdout == "0"
  rescue:
    - name: Print error message
      debug:
        msg: "Host CPU doesn't support virtualization"
  tags: 
    - virtualization
    - desktop
    - server

- name: Check host CPU arch
  block:
    - name: Check if host CPU is 64-bit
      command: "egrep -c ' lm ' /proc/cpuinfo"
      changed_when: no
      register: bitinfo_output
      failed_when: bitinfo_output.stdout == "0"
  rescue:
    - name: Print error message
      debug:
        msg: "Host CPU is not 64-bit"
  tags: 
    - virtualization
    - desktop
    - server

- name: Install virtualization tooling
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ virtualization_packages|flatten(levels=1) }}"
  when: cpuinfo_output.stdout != "0" and bitinfo_output.stdout != "0"
  tags: 
    - virtualization
    - desktop
    - server

- name: Setting up libvirt/kvm group membership 
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt,kvm
    append: yes
  ignore_errors: true
  tags: 
    - virtualization
    - desktop
    - server

- name: Sync uvtool images
  command: "uvt-simplestreams-libvirt sync release={{ item }} arch={{ img_arch }}"
  loop: "{{ uvtool_images|flatten(levels=1) }}"
  ignore_errors: true
  tags: 
    - virtualization
    - desktop
    - server