---
- name: Update and upgrade via apt
  apt:
    update_cache: yes
    upgrade: dist
  tags:
    - base
    - server
    - desktop 

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ base_packages }}" 
  tags:
    - base
    - server
    - desktop